SELECT CONCAT('/home/grep/src/', A.BOARD_ID, '/', A.FILE_ID, A.FILE_NAME, A.FILE_EXT)
AS FILE_PATH

FROM USED_GOODS_FILE AS A

JOIN USED_GOODS_BOARD  AS B
ON A.BOARD_ID = B.BOARD_ID

WHERE B.VIEWS = (
    SELECT MAX(B1.VIEWS) 
    FROM USED_GOODS_BOARD AS B1 
)
ORDER BY A.FILE_ID DESC