SELECT A.FLAVOR
FROM FIRST_HALF AS A
    INNER JOIN
    (
        SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS C
        FROM JULY
        GROUP BY FLAVOR
    ) AS B ON A.FLAVOR = B.FLAVOR
ORDER BY (A.TOTAL_ORDER + C) DESC
LIMIT 3;