SELECT
  CASE
    WHEN MONTH(ec.DIFFERENTIATION_DATE) BETWEEN 1 AND 3 THEN '1Q'
    WHEN MONTH(ec.DIFFERENTIATION_DATE) BETWEEN 4 AND 6 THEN '2Q'
    WHEN MONTH(ec.DIFFERENTIATION_DATE) BETWEEN 7 AND 9 THEN '3Q'
    WHEN MONTH(ec.DIFFERENTIATION_DATE) BETWEEN 10 AND 12 THEN '4Q'
  END AS QUARTER,
  COUNT(1) AS ECOLI_COUNT
FROM ECOLI_DATA AS ec
GROUP BY QUARTER
ORDER BY QUARTER
