SELECT CAR_ID,
CASE
    WHEN MAX(END_DATE) >= "2022-10-16"
    THEN '대여중'
    WHEN MAX(END_DATE) < "2022-10-16"
    THEN '대여 가능'
END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= "2022-10-16"
GROUP BY CAR_ID
ORDER BY CAR_ID DESC