SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_BOARD AS A, USED_GOODS_REPLY AS B
WHERE DATE_FORMAT(A.CREATED_DATE, "%Y-%m-%d") BETWEEN '2022-10-01' AND '2022-10-31'
AND A.BOARD_ID = B.BOARD_ID
ORDER BY B.CREATED_DATE, A.TITLE