SELECT A.PRODUCT_ID, A.PRODUCT_NAME, (A.PRICE * amount) AS TOTAL_SALES
FROM FOOD_PRODUCT AS A INNER JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) as amount, PRODUCE_DATE 
    FROM FOOD_ORDER
    WHERE DATE_FORMAT(PRODUCE_DATE, "%Y-%m") = "2022-05"
    GROUP BY PRODUCT_ID
) AS B ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID