SELECT A.APNT_NO, C.PT_NAME, C.PT_NO, A.MCDP_CD, B.DR_NAME, A.APNT_YMD
FROM APPOINTMENT AS A INNER JOIN DOCTOR AS B ON A.MDDR_ID = B.DR_ID
INNER JOIN PATIENT AS C ON A.PT_NO = C.PT_NO
WHERE DATE_FORMAT(A.APNT_YMD, "%Y-%m-%d") = "2022-04-13" AND A.APNT_CNCL_YMD IS NULL
AND B.MCDP_CD = "CS"
ORDER BY A.APNT_YMD