WITH MAX_FISH AS (
    SELECT
        fi.FISH_TYPE,
        MAX(fi.LENGTH) AS MAX_LENGTH
    FROM
        FISH_INFO as fi
    GROUP BY
        fi.FISH_TYPE
)

SELECT
    fi.ID AS ID,
    fn.FISH_NAME AS FISH_NAME,
    fi.LENGTH AS LENGTH
FROM
    FISH_INFO fi
JOIN
    MAX_FISH mf
ON
    fi.FISH_TYPE = mf.FISH_TYPE
    AND fi.LENGTH = mf.MAX_LENGTH
JOIN
    FISH_NAME_INFO fn
ON
    fi.FISH_TYPE = fn.FISH_TYPE
ORDER BY
    fi.ID ASC;
