SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, C
FROM REST_INFO AS A
    INNER JOIN 
    (
        SELECT  REST_ID, REVIEW_ID, ROUND(AVG(REVIEW_SCORE), 2) AS C
        FROM REST_REVIEW
        GROUP BY REST_ID
    ) AS B ON A.REST_ID = B.REST_ID
WHERE A.ADDRESS LIKE "서울%"
ORDER BY C DESC, A.FAVORITES DESC